#! /bin/bash

#
# Script used to create an SD image
#   -- Run as 'root'
#   -- Requires worker script 'mkcard.sh' to be on $PATH
#

# Evaluate arguments so variables can be easily overridden
for i in $*; do
  if echo $i | grep -q '='; then
    eval $i
  fi
done

if [ $# -lt 3 ]; then
  echo "usage: make_sd <dev> <uImage> <rootfs> [MLO=mlo] [UBOOT=uboot] [UBOOT_IMG=uboot.img] [IMAGE_NAME=uImage]"
  exit 1
fi

DEV=$1
UIMAGE=$2
ROOTFS=$3
MLO=${MLO:-""}
UBOOT=${UBOOT:-""}
UBOOT_IMG=${UBOOT_IMG:-""}
UENV=${UENV:=""}
IMAGE_NAME=${IMAGE_NAME:="zImage"}

MDEV=`basename ${DEV}`
if ! fgrep -q ${MDEV} /proc/partitions; then
  echo "*** Are you sure?  ${DEV} is not in partition list"
  exit 1
fi

echo "========================================"
echo ""
echo "About to create SD:"
echo "  SD device = ${DEV}"
if [ "${UIMAGE}" != "none" ]; then
  UIMAGE=`readlink -e ${UIMAGE}`
  echo "  uImage file = ${UIMAGE}"
fi
ROOTFS=`readlink -e ${ROOTFS}`
echo "  root file system = ${ROOTFS}"
if [ "x$MLO" != "x" ]; then
  MLO=`readlink -e $MLO`
  echo "  MLO = ${MLO}"
fi
if [ "x$UBOOT" != "x" ]; then
  UBOOT=`readlink -e $UBOOT`
  echo "  UBOOT = ${UBOOT}"
fi
if [ "x$UBOOT_IMG" != "x" ]; then
  UBOOT_IMG=`readlink -e $UBOOT_IMG`
  echo "  UBOOT_IMG = ${UBOOT_IMG}"
fi
if [ "x$UENV" != "x" ]; then
  UENV=`readlink -e $UENV`
  echo "  UENV = ${UENV}"
fi
echo ""
echo "========================================"

read -p "Continue? " OK

if [ "${OK}" == "yes" ]; then
  echo "****************************************"
  echo "Format SD card"
  mkcard.sh ${DEV} >/tmp/mkcard.log 2>&1
  echo "****************************************"
  mkdir -p /tmp/media
  mount ${DEV}1 /tmp/media
  if [ "x$MLO" != "x" ]; then
    echo "Install MLO"
    cp ${MLO} /tmp/media/MLO
  fi
  if [ "x$UBOOT" != "x" ]; then
    echo "Install U-Boot"
    cp ${UBOOT} /tmp/media/u-boot.bin
  fi
  if [ "x$UBOOT_IMG" != "x" ]; then
    echo "Install U-Boot [img]"
    cp ${UBOOT_IMG} /tmp/media/u-boot.img
  fi
  if [ "x$UENV" != "x" ]; then
    echo "Install U-Boot environment"
    cp ${UENV} /tmp/media/uEnv.txt
  fi
  echo "Copy kernel"
  if [ "${UIMAGE}" != "none" ]; then
    cp ${UIMAGE} /tmp/media/${IMAGE_NAME}
    cp ${UIMAGE} /tmp/media/${IMAGE_NAME}.bin
  fi
  sync
  umount /tmp/media
  echo "****************************************"
  echo "Install root file system"
  mount ${DEV}2 /tmp/media
  if `echo ${ROOTFS} | fgrep -q bz2`; then
    tar -jxpf ${ROOTFS} -C /tmp/media
  else
    tar -zxpf ${ROOTFS} -C /tmp/media
  fi
  if [ "${UIMAGE}" != "none" ]; then
    mkdir -p /tmp/media/boot
    cp ${UIMAGE} /tmp/media/boot/${IMAGE_NAME}
    sync
  fi
  umount /tmp/media
  sync
fi


