#! /bin/bash

# Upload tarballs, etc, from a Poky/Yocto build tree to the common source tree
YOCTO="$(dirname $0)/../.."
if [ ! -d downloads ]; then
  echo "*** This script must be run in a Poky/Yocto build tree"
  exit 1
fi
cd downloads
find . -maxdepth 1 -type f | grep -v '.lock$' | grep -v '.done$' >/tmp/files.$$
rsync -auv --files-from=/tmp/files.$$ . $(readlink ${YOCTO}/sources)
